#!/bin/sh

# Nginx entrypoint - Waits for certificate and starts Nginx

DOMAIN=${DOMAIN:-file.bytrix.my.id}
CERT_PATH="/etc/letsencrypt/live/$DOMAIN"
CERT_FILE="$CERT_PATH/fullchain.pem"
MAX_WAIT=120
ELAPSED=0

echo "=================================================="
echo "Bytrix Nginx - Auto SSL Startup"
echo "=================================================="
echo ""
echo "Domain: $DOMAIN"
echo "Certificate Path: $CERT_FILE"
echo ""

# Wait for certificate to be generated (max 2 minutes)
echo "Waiting for SSL certificate..."
while [ ! -f "$CERT_FILE" ]; do
    if [ $ELAPSED -ge $MAX_WAIT ]; then
        echo "⚠ Certificate not found after 120 seconds"
        echo "  Nginx will start with self-signed cert"
        echo "  Certificate will be generated by Certbot in parallel"
        break
    fi
    
    ELAPSED=$((ELAPSED + 1))
    echo "  Checking... ($ELAPSED/$MAX_WAIT seconds)"
    sleep 1
done

if [ -f "$CERT_FILE" ]; then
    echo "✓ Certificate found!"
    openssl x509 -in "$CERT_FILE" -noout -enddate
else
    echo "⚠ Certificate not ready yet, using placeholder"
fi

echo ""
echo "Starting Nginx..."
echo "=================================================="
echo ""

# Test nginx config
echo "Testing Nginx configuration..."
nginx -t

# Start Nginx in foreground
exec nginx -g "daemon off;"
