@echo off
REM Bytrix API - Auto SSL Setup (Windows Batch)
REM Usage: setup-ssl.bat file.bytrix.my.id admin@example.com

setlocal enabledelayedexpansion

if "%~1"=="" (
    echo ERROR: Domain not provided
    echo Usage: setup-ssl.bat ^<domain^> ^<email^>
    echo Example: setup-ssl.bat file.bytrix.my.id admin@example.com
    exit /b 1
)

set DOMAIN=%~1
set EMAIL=%~2
if "!EMAIL!"=="" set EMAIL=admin@example.com

echo.
echo ========================================================
echo   Bytrix API - Auto SSL Setup (Let's Encrypt + Caddy)
echo ========================================================
echo.
echo Configuration:
echo   Domain: %DOMAIN%
echo   Email:  %EMAIL%
echo.

REM Create directories
echo Creating SSL directories...
if not exist "ssl\letsencrypt" mkdir ssl\letsencrypt
if not exist "ssl\certbot" mkdir ssl\certbot
if not exist "caddy\data" mkdir caddy\data
if not exist "caddy\config" mkdir caddy\config
if not exist "logs\nginx" mkdir logs\nginx
echo OK
echo.

REM Update .env file
echo Updating .env file...
if exist .env (
    powershell -Command "(Get-Content .env) -replace 'DOMAIN=.*', 'DOMAIN=https://%DOMAIN%' | Set-Content .env"
) else (
    (echo DOMAIN=https://%DOMAIN%) > .env
)
echo OK
echo.

REM Update nginx.conf
echo Updating Nginx configuration...
if exist nginx.conf (
    powershell -Command "(Get-Content nginx.conf) -replace 'DOMAIN_PLACEHOLDER', '%DOMAIN%' | Set-Content nginx.conf"
)
echo OK
echo.

REM Create .env.docker
echo Creating docker-compose .env file...
(
    echo # Generated by setup-ssl.bat
    echo DOMAIN=https://%DOMAIN%
    echo EMAIL=%EMAIL%
) > .env.docker
echo OK
echo.

echo ========================================================
echo SETUP COMPLETE!
echo ========================================================
echo.
echo NEXT STEPS:
echo.
echo 1. Make sure ports 80 and 443 are open
echo    Check firewall and DNS: nslookup %DOMAIN%
echo.
echo 2. Start Docker containers:
echo    docker-compose up -d
echo.
echo 3. Generate Let's Encrypt certificate:
echo    docker-compose exec certbot certbot certonly --webroot ^
echo      -w /var/www/certbot -d %DOMAIN% --email %EMAIL% --agree-tos --non-interactive
echo.
echo 4. Verify SSL certificate:
echo    docker-compose exec nginx openssl x509 -in ^
echo      /etc/letsencrypt/live/%DOMAIN%/fullchain.pem -text -noout
echo.
echo 5. Test access:
echo    curl -k https://%DOMAIN%/health
echo.
echo MONITORING:
echo   docker-compose logs -f
echo   docker-compose logs nginx
echo   docker-compose logs certbot
echo.
echo CONFIGURATION FILES:
echo   - docker-compose.yml    (Full stack config)
echo   - nginx.conf            (Nginx with SSL)
echo   - caddy/Caddyfile       (Caddy backup)
echo   - .env                  (Updated with domain)
echo   - .env.docker           (Docker variables)
echo   - ssl/                  (Certificates storage)
echo.
echo ========================================================
echo.
