#!/usr/bin/env bash
# Bytrix API - Auto SSL Setup Script
# Usage: bash setup-ssl.sh file.bytrix.my.id your-email@example.com

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   Bytrix API - Auto SSL Setup (Let's Encrypt + Caddy)     ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}\n"

# Check if domain provided
if [ -z "$1" ]; then
    echo -e "${RED}❌ Error: Domain not provided${NC}"
    echo -e "${YELLOW}Usage: bash setup-ssl.sh <domain> <email>${NC}"
    echo -e "${YELLOW}Example: bash setup-ssl.sh file.bytrix.my.id admin@example.com${NC}"
    exit 1
fi

DOMAIN=$1
EMAIL=${2:-admin@example.com}

echo -e "${YELLOW}📋 Configuration:${NC}"
echo -e "  Domain: ${GREEN}${DOMAIN}${NC}"
echo -e "  Email:  ${GREEN}${EMAIL}${NC}\n"

# 1. Create SSL directories
echo -e "${YELLOW}📁 Creating SSL directories...${NC}"
mkdir -p ssl/letsencrypt
mkdir -p ssl/certbot
mkdir -p caddy/data
mkdir -p caddy/config
mkdir -p logs/nginx
echo -e "${GREEN}✓ Directories created${NC}\n"

# 2. Update .env file with domain
echo -e "${YELLOW}🔧 Updating .env file...${NC}"
if [ -f .env ]; then
    # Update DOMAIN in .env if exists
    if grep -q "^DOMAIN=" .env; then
        sed -i "s|^DOMAIN=.*|DOMAIN=https://${DOMAIN}|" .env
        echo -e "${GREEN}✓ Updated DOMAIN in .env${NC}"
    else
        echo "DOMAIN=https://${DOMAIN}" >> .env
        echo -e "${GREEN}✓ Added DOMAIN to .env${NC}"
    fi
else
    echo -e "${RED}⚠️  .env file not found. Creating template...${NC}"
    cp .env.example .env 2>/dev/null || echo "DOMAIN=https://${DOMAIN}" > .env
    echo -e "${GREEN}✓ .env created${NC}"
fi

# 3. Update nginx.conf with domain
echo -e "${YELLOW}🔗 Updating Nginx configuration...${NC}"
if [ -f nginx.conf ]; then
    # Replace placeholder with actual domain
    sed -i "s|DOMAIN_PLACEHOLDER|${DOMAIN}|g" nginx.conf
    echo -e "${GREEN}✓ Updated Nginx config with domain${NC}"
else
    echo -e "${RED}⚠️  nginx.conf not found${NC}"
fi

# 4. Create temporary self-signed cert for initial startup
echo -e "${YELLOW}🔐 Creating temporary self-signed certificate...${NC}"
mkdir -p ssl/letsencrypt/live/${DOMAIN}

openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout ssl/letsencrypt/live/${DOMAIN}/privkey.pem \
    -out ssl/letsencrypt/live/${DOMAIN}/fullchain.pem \
    -subj "/CN=${DOMAIN}" 2>/dev/null || true

echo -e "${GREEN}✓ Self-signed certificate created${NC}\n"

# 5. Update docker-compose.yml with DOMAIN
echo -e "${YELLOW}📝 Creating docker-compose .env file...${NC}"
cat > .env.docker << EOF
# Generated by setup-ssl.sh
DOMAIN=https://${DOMAIN}
EMAIL=${EMAIL}
EOF
echo -e "${GREEN}✓ Docker environment file created${NC}\n"

# 6. Display instructions
echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✓ Setup complete!${NC}\n"

echo -e "${YELLOW}📋 Next Steps:${NC}"
echo -e "  1. Make sure ports 80 and 443 are open:"
echo -e "     ${BLUE}ufw allow 80/tcp${NC}"
echo -e "     ${BLUE}ufw allow 443/tcp${NC}\n"

echo -e "  2. Start containers with Docker Compose:"
echo -e "     ${BLUE}docker-compose up -d${NC}\n"

echo -e "  3. Generate Let's Encrypt certificate:"
echo -e "     ${BLUE}docker-compose exec certbot certbot certonly --webroot -w /var/www/certbot -d ${DOMAIN} --email ${EMAIL} --agree-tos --non-interactive${NC}\n"

echo -e "  4. Verify SSL certificate:"
echo -e "     ${BLUE}docker-compose exec nginx openssl x509 -in /etc/letsencrypt/live/${DOMAIN}/fullchain.pem -text -noout${NC}\n"

echo -e "  5. Check status:"
echo -e "     ${BLUE}curl -k https://${DOMAIN}/health${NC}\n"

echo -e "${YELLOW}🔄 SSL Auto-Renewal:${NC}"
echo -e "  Certbot will automatically renew certificates 30 days before expiry.\n"

echo -e "${YELLOW}🔧 Configuration Files:${NC}"
echo -e "  • docker-compose.yml - Full stack configuration"
echo -e "  • nginx.conf - Nginx with SSL"
echo -e "  • caddy/Caddyfile - Caddy backup config"
echo -e "  • .env - Environment variables"
echo -e "  • .env.docker - Docker-specific variables\n"

echo -e "${YELLOW}📊 Monitoring Logs:${NC}"
echo -e "  • ${BLUE}docker-compose logs nginx${NC}"
echo -e "  • ${BLUE}docker-compose logs certbot${NC}"
echo -e "  • ${BLUE}docker-compose logs bytrix-api${NC}"
echo -e "  • ${BLUE}docker-compose logs caddy${NC}\n"

echo -e "${YELLOW}🛠️  Troubleshooting:${NC}"
echo -e "  • Check firewall: ${BLUE}sudo ufw status${NC}"
echo -e "  • Check ports: ${BLUE}sudo netstat -tulpn | grep LISTEN${NC}"
echo -e "  • Restart containers: ${BLUE}docker-compose restart${NC}"
echo -e "  • Check certificate: ${BLUE}ls -la ssl/letsencrypt/live/${DOMAIN}/{{NC}\n"

echo -e "${BLUE}════════════════════════════════════════════════════════════${NC}\n"
