# Bytrix API - Auto SSL Setup Script (Windows PowerShell)
# Usage: .\setup-ssl.ps1 -Domain file.bytrix.my.id -Email admin@example.com

param(
    [Parameter(Mandatory=$true)]
    [string]$Domain,
    
    [Parameter(Mandatory=$false)]
    [string]$Email = "admin@example.com"
)

$ErrorActionPreference = "Stop"

# Colors
$Green = "Green"
$Red = "Red"
$Yellow = "Yellow"
$Blue = "Cyan"

function Write-Title {
    Write-Host "╔════════════════════════════════════════════════════════════╗" -ForegroundColor $Blue
    Write-Host "║   Bytrix API - Auto SSL Setup (Let's Encrypt + Caddy)     ║" -ForegroundColor $Blue
    Write-Host "╚════════════════════════════════════════════════════════════╝" -ForegroundColor $Blue
    Write-Host ""
}

function Write-Step($message) {
    Write-Host $message -ForegroundColor $Yellow
}

function Write-Success($message) {
    Write-Host "✓ $message" -ForegroundColor $Green
}

function Write-Error($message) {
    Write-Host "✗ $message" -ForegroundColor $Red
}

Write-Title

Write-Host "📋 Configuration:" -ForegroundColor $Yellow
Write-Host "  Domain: $Domain" -ForegroundColor $Green
Write-Host "  Email:  $Email" -ForegroundColor $Green
Write-Host ""

# 1. Create SSL directories
Write-Step "📁 Creating SSL directories..."
@(
    "ssl\letsencrypt",
    "ssl\certbot",
    "caddy\data",
    "caddy\config",
    "logs\nginx"
) | ForEach-Object {
    if (-not (Test-Path $_)) {
        New-Item -ItemType Directory -Path $_ -Force | Out-Null
    }
}
Write-Success "Directories created"
Write-Host ""

# 2. Update .env file
Write-Step "🔧 Updating .env file..."
if (Test-Path ".env") {
    $envContent = Get-Content ".env"
    if ($envContent -match "^DOMAIN=") {
        $envContent = $envContent -replace "^DOMAIN=.*", "DOMAIN=https://$Domain"
    } else {
        $envContent += "`nDOMAIN=https://$Domain"
    }
    Set-Content -Path ".env" -Value $envContent
    Write-Success "Updated DOMAIN in .env"
} else {
    Write-Host "DOMAIN=https://$Domain" | Out-File -FilePath ".env" -Encoding UTF8
    Write-Success ".env created with DOMAIN"
}
Write-Host ""

# 3. Update nginx.conf
Write-Step "🔗 Updating Nginx configuration..."
if (Test-Path "nginx.conf") {
    $nginxContent = Get-Content "nginx.conf" -Raw
    $nginxContent = $nginxContent -replace "DOMAIN_PLACEHOLDER", $Domain
    Set-Content -Path "nginx.conf" -Value $nginxContent
    Write-Success "Updated Nginx config"
} else {
    Write-Error "nginx.conf not found"
}
Write-Host ""

# 4. Create temp self-signed cert
Write-Step "🔐 Creating temporary self-signed certificate..."
$certPath = "ssl\letsencrypt\live\$Domain"
if (-not (Test-Path $certPath)) {
    New-Item -ItemType Directory -Path $certPath -Force | Out-Null
}

# Using OpenSSL (if available)
$opensslPath = Get-Command openssl -ErrorAction SilentlyContinue
if ($opensslPath) {
    & openssl req -x509 -nodes -days 365 -newkey rsa:2048 `
        -keyout "$certPath\privkey.pem" `
        -out "$certPath\fullchain.pem" `
        -subj "/CN=$Domain" 2>$null
    Write-Success "Self-signed certificate created"
} else {
    Write-Host "⚠️  OpenSSL not found. Please install it or use online tools." -ForegroundColor Yellow
}
Write-Host ""

# 5. Create docker-compose .env file
Write-Step "📝 Creating docker-compose .env file..."
$dockerEnv = @"
# Generated by setup-ssl.ps1
DOMAIN=https://$Domain
EMAIL=$Email
"@
$dockerEnv | Out-File -FilePath ".env.docker" -Encoding UTF8
Write-Success "Docker environment file created"
Write-Host ""

# 6. Display instructions
Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor $Blue
Write-Success "Setup complete!"
Write-Host ""

Write-Host "📋 Next Steps:" -ForegroundColor $Yellow
Write-Host ""
Write-Host "1️⃣  Make sure ports 80 and 443 are open:" -ForegroundColor $Yellow
Write-Host "   $Domain should be pointing to your server IP (165.22.244.107)" -ForegroundColor $Blue
Write-Host ""

Write-Host "2️⃣  Start containers with Docker Compose:" -ForegroundColor $Yellow
Write-Host "   docker-compose up -d" -ForegroundColor $Blue
Write-Host ""

Write-Host "3️⃣  Generate Let's Encrypt certificate:" -ForegroundColor $Yellow
Write-Host "   docker-compose exec certbot certbot certonly --webroot -w /var/www/certbot -d $Domain --email $Email --agree-tos --non-interactive" -ForegroundColor $Blue
Write-Host ""

Write-Host "4️⃣  Verify SSL certificate:" -ForegroundColor $Yellow
Write-Host "   docker-compose exec nginx openssl x509 -in /etc/letsencrypt/live/$Domain/fullchain.pem -text -noout" -ForegroundColor $Blue
Write-Host ""

Write-Host "5️⃣  Check status:" -ForegroundColor $Yellow
Write-Host "   curl -k https://$Domain/health" -ForegroundColor $Blue
Write-Host ""

Write-Host "🔄 SSL Auto-Renewal:" -ForegroundColor $Yellow
Write-Host "   Certbot will automatically renew certificates 30 days before expiry." -ForegroundColor $Blue
Write-Host ""

Write-Host "🔧 Configuration Files:" -ForegroundColor $Yellow
Write-Host "   • docker-compose.yml - Full stack configuration" -ForegroundColor $Blue
Write-Host "   • nginx.conf - Nginx with SSL" -ForegroundColor $Blue
Write-Host "   • caddy/Caddyfile - Caddy backup config" -ForegroundColor $Blue
Write-Host "   • .env - Environment variables" -ForegroundColor $Blue
Write-Host "   • .env.docker - Docker-specific variables" -ForegroundColor $Blue
Write-Host ""

Write-Host "📊 Monitoring Logs:" -ForegroundColor $Yellow
Write-Host "   • docker-compose logs nginx" -ForegroundColor $Blue
Write-Host "   • docker-compose logs certbot" -ForegroundColor $Blue
Write-Host "   • docker-compose logs bytrix-api" -ForegroundColor $Blue
Write-Host "   • docker-compose logs caddy" -ForegroundColor $Blue
Write-Host ""

Write-Host "🛠️  Troubleshooting:" -ForegroundColor $Yellow
Write-Host "   • Check domain DNS: nslookup $Domain" -ForegroundColor $Blue
Write-Host "   • Check ports: netstat -ano | findstr :80" -ForegroundColor $Blue
Write-Host "   • Restart containers: docker-compose restart" -ForegroundColor $Blue
Write-Host "   • View logs: docker-compose logs -f" -ForegroundColor $Blue
Write-Host ""

Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor $Blue
Write-Host ""
